(display 12)
(display 3)
(newline)
(display "so real")
(newline)
(display "so real\n")
(display "so \\real\n")
(display "so \"real\n")
(display "so\nreal\n")
(display 'yay)
(newline)
(display '(+ 1 2))
(newline)
