(define i (open-input-file "samples/hello.txt"))
(display (read-char i))
(newline)
(display (read-char i))
(newline)
(display (read-char i))
(newline)
(display (read-char i))
(newline)
(display (read-char i))
(newline)
(display (read-char i))
(newline)
(display (read-char i))
(newline)
(display (read-char i))
(newline)

(display (read-char i))
(newline)
(display (read-char i))
(newline)
(display (read-char i))
(newline)
(display (read-char i))
(newline)
