(display (string-append "so " "real"))
(newline)
(display (string-append "so " "real" " desu"))
(newline)
(display (string-append "" "" ""))
(newline)
(display (string-append "yay"))
(newline)
(display (string-append))
(newline)
